version: '3'

services:
  ampache:
    image: ampache/ampache:latest
    container_name: ampache
    restart: unless-stopped
    ports:
      - 4040:80
    environment:
      PGID: 1000
      PUID: 1000
    # user: 1000:1000
    volumes:
      # NOTE: mark the config directory as 777
      # `sudo chmod -Rv 777 ~/data/docker_data/ampache/config`
      - /home/murali/data00/docker_data/ampache/config:/var/www/config:rw
      - /home/murali/data00/docker_data/ampache/log:/var/log/ampache:rw
      - /home/murali/data00/Songs:/media:ro
      - /home/murali/data00/docker_data/ampache/mysql:/var/lib/mysql:rw
